exports.seed = function(knex: any) {
  // Deletes ALL existing entries
  return knex('products').del()
    .then(function () {
      // Inserts seed entries
      return knex('products').insert(
        products.map(product => {
          return {
            ...product,
            created_at: new Date(),
            updated_at: new Date(),
          }
        })
      )
    })
}

// category_id: 1 = Smartphones, 2 = Tablets, 3 = Accessories
// status_id: 1 = Active/Available เสมอ
// user_id: 1 อ้างอิงถึง Demo User คนแรกที่สมัครผ่าน POST /api/auth/register
const products = [
  // --- Smartphones (category_id: 1) ---
  {
    name: 'iPhone 15 Pro',
    description: 'สมาร์ทโฟนระดับเรือธงจาก Apple พร้อมชิป A17 Pro และดีไซน์ไทเทเนียมสุดหรู',
    barcode: 'PHONE001',
    image: 'iphone15pro.jpg',
    stock: 20,
    price: 39900,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'Samsung Galaxy S24',
    description: 'สมาร์ทโฟนเรือธง Android พร้อมฟีเจอร์ AI อัจฉริยะ และหน้าจอ Dynamic AMOLED คมชัดสดใส',
    barcode: 'PHONE002',
    image: 'samsung_s24.jpg',
    stock: 20,
    price: 29900,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'Xiaomi 14',
    description: 'สมาร์ทโฟนประสิทธิภาพสูง พร้อมเลนส์กล้องระดับมืออาชีพจาก Leica',
    barcode: 'PHONE003',
    image: 'xiaomi14.jpg',
    stock: 20,
    price: 24900,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'OPPO Find X7',
    description: 'สมาร์ทโฟนเรือธงทรงพลัง พร้อมความสามารถในการถ่ายภาพพอร์ตเทรตที่ยอดเยี่ยม',
    barcode: 'PHONE004',
    image: 'oppo_findx7.jpg',
    stock: 20,
    price: 27900,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'Vivo X100',
    description: 'สมาร์ทโฟนระดับพรีเมียมพร้อมเลนส์ ZEISS และรองรับระบบชาร์จไว',
    barcode: 'PHONE005',
    image: 'vivo_x100.jpg',
    stock: 20,
    price: 26900,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'iPhone 14',
    description: 'สมาร์ทโฟนยอดนิยมจาก Apple มาพร้อมระบบกล้องคู่และแบตเตอรี่ใช้งานได้ยาวนานตลอดวัน',
    barcode: 'PHONE006',
    image: 'iphone14.jpg',
    stock: 20,
    price: 29900,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'Samsung Galaxy A55',
    description: 'สมาร์ทโฟนระดับกลาง ดีไซน์พรีเมียม หน้าจอลื่นไหล และใช้งานได้คุ้มค่า',
    barcode: 'PHONE007',
    image: 'samsung_a55.jpg',
    stock: 20,
    price: 13990,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'Google Pixel 8',
    description: 'สมาร์ทโฟนจาก Google พร้อมชิป Tensor G3 และระบบประมวลผลภาพถ่ายด้วย AI สุดล้ำ',
    barcode: 'PHONE008',
    image: 'google_pixel8.jpg',
    stock: 20,
    price: 25900,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'OnePlus 12',
    description: 'สมาร์ทโฟนสเปกแรงเพื่อการใช้งานที่ลื่นไหล พร้อมกล้องร่วมพัฒนาโดย Hasselblad',
    barcode: 'PHONE009',
    image: 'oneplus_12.jpg',
    stock: 20,
    price: 28900,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'Sony Xperia 1 VI',
    description: 'สมาร์ทโฟนเรือธงสำหรับคนรักการถ่ายภาพและบันเทิง พร้อมหน้าจอ 4K OLED คมชัดสมจริง',
    barcode: 'PHONE010',
    image: 'sony_xperia1vi.jpg',
    stock: 20,
    price: 38900,
    category_id: 1,
    user_id: 1,
    status_id: 1,
  },

  // --- Tablets (category_id: 2) ---
  {
    name: 'iPad Pro 11"',
    description: 'แท็บเล็ตทรงพลังขับเคลื่อนด้วยชิป M-series และหน้าจอ Liquid Retina คมชัดตระการตา',
    barcode: 'TABLET001',
    image: 'ipad_pro.jpg',
    stock: 15,
    price: 32900,
    category_id: 2,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'Xiaomi Pad 6',
    description: 'แท็บเล็ต Android เอนกประสงค์ ตอบโจทย์ทั้งการทำงานและความบันเทิง',
    barcode: 'TABLET002',
    image: 'xiaomi_pad6.jpg',
    stock: 15,
    price: 12990,
    category_id: 2,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'Samsung Galaxy Tab S9',
    description: 'แท็บเล็ตพรีเมียมพร้อมปากกา S Pen ในชุด และหน้าจอ AMOLED เต็มตา',
    barcode: 'TABLET003',
    image: 'galaxy_tabs9.jpg',
    stock: 15,
    price: 28900,
    category_id: 2,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'iPad Air',
    description: 'แท็บเล็ตน้ำหนักเบา ดีไซน์บางเฉียบ ออกแบบมาเพื่อการทำงานและความคิดสร้างสรรค์',
    barcode: 'TABLET004',
    image: 'ipad_air.jpg',
    stock: 15,
    price: 23900,
    category_id: 2,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'Lenovo Tab P12',
    description: 'แท็บเล็ตเพื่อความบันเทิงจอใหญ่ พร้อมลำโพง JBL 4 ตัวเสียงกระหึ่ม',
    barcode: 'TABLET005',
    image: 'lenovo_tab_p12.jpg',
    stock: 15,
    price: 14900,
    category_id: 2,
    user_id: 1,
    status_id: 1,
  },

  // --- Accessories (category_id: 3) ---
  {
    name: 'Wireless Earbuds Pro',
    description: 'หูฟังไร้สายระบบตัดเสียงรบกวนแอคทีฟ ให้เสียงความคมชัดสูงระดับไฮไฟ',
    barcode: 'ACC001',
    image: 'earbuds_pro.jpg',
    stock: 30,
    price: 4990,
    category_id: 3,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'Fast Charger 45W',
    description: 'หัวชาร์จเร็ว USB-C กำลังไฟสูง รองรับการใช้งานกับหลากหลายแบรนด์อุปกรณ์',
    barcode: 'ACC002',
    image: 'charger_45w.jpg',
    stock: 30,
    price: 890,
    category_id: 3,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'MagSafe Power Bank 10000mAh',
    description: 'แบตเตอรี่สำรองไร้สายแบบแม่เหล็ก พกพาสะดวก ชาร์จได้ทุกที่ทุกเวลา',
    barcode: 'ACC003',
    image: 'powerbank.jpg',
    stock: 25,
    price: 1590,
    category_id: 3,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'Smart Watch Series 9',
    description: 'นาฬิกาอัจฉริยะสำหรับติดตามสุขภาพและออกกำลังกาย พร้อมหน้าจอ Retina สว่างคมชัด',
    barcode: 'ACC004',
    image: 'smartwatch.jpg',
    stock: 20,
    price: 12900,
    category_id: 3,
    user_id: 1,
    status_id: 1,
  },
  {
    name: 'Bluetooth Speaker Portable',
    description: 'ลำโพงไร้สายพกพา กันน้ำ เสียงเบสแน่น แบตเตอรี่อึดใช้งานได้นาน',
    barcode: 'ACC005',
    image: 'bluetooth_speaker.jpg',
    stock: 20,
    price: 1990,
    category_id: 3,
    user_id: 1,
    status_id: 1,
  },
]